
Get http://localhost:3001/api/notes

### 
POST http://localhost:80/api/notes
Content-Type: application/json

{
    "content": "Postman is good in testing backend again",
    "important": true
}

###
POST http://localhost:80/api/persons
Content-Type: application/json

{
    "name": "Alex Roger",
    "number": "23213-121313",
    "id": 5
}
